#pragma config(Sensor, in1,    MainLiftPot,    sensorPotentiometer)
#pragma config(Sensor, in2,    MogoPot,        sensorPotentiometer)
#pragma config(Sensor, in3,    TopLiftPot,     sensorPotentiometer)
#pragma config(Sensor, in5,    Gyro,           sensorGyro)
#pragma config(Sensor, in6,    ConePot,        sensorPotentiometer)
#pragma config(Sensor, dgtl1,  LEncoder,       sensorQuadEncoder)
#pragma config(Sensor, dgtl3,  REncoder,       sensorQuadEncoder)
#pragma config(Motor,  port2,           LDrive,        tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port3,           LMainLift,     tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port4,           ConeIntake,    tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port5,           LMogoIntake,   tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port6,           RMogoIntake,   tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port7,           TopLift,       tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port8,           RMainLift,     tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port9,           RDrive,        tmotorVex393_MC29, openLoop, reversed)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#pragma platform(VEX2)

// Select Download method as "competition"
#pragma competitionControl(Competition)

#include "lift/lift.h"
#include "intake/intake.h"
#include "drive/drive.h"
#include "programs/autostack.h"
#include "Autons/autons.h"

#include "lift/lift.c"
#include "intake/intake.c"
#include "drive/drive.c"
#include "programs/autostack.c"
#include "Autons/Mogo22.c"
#include "Autons/Mogo24.c"
#include "Autons/ProgramingSkills.c"
#include "Autons/ScoreOn20.c"
#include "Autons/StationaryGoal.c"

#include "Vex_Competition_Includes.c"

int selectedAuton = 0;

task selector() {
	int NUM_AUTONS = 4;
	string autonNames[] = {"ONLY DEPLOY", "2PT STAGO", "24PT MOGO", "PSKILLS", "22PT MOGO"};

	while (!bIfiAutonomousMode) {
		// change autons by using buttons; left and right cycle through autons, center inverts direction
		if (nLCDButtons == 1) {
			waitUntil(nLCDButtons == 0);
			selectedAuton--;
		} else if (nLCDButtons == 2) {
			waitUntil(nLCDButtons == 0);
			selectedAuton *= -1;
		} else if (nLCDButtons == 4) {
			waitUntil(nLCDButtons == 0);
			selectedAuton++;
		}

		// loop over to the other end of the list if no more autons to go through
		if (abs(selectedAuton) > NUM_AUTONS) {
			selectedAuton = -sgn(selectedAuton) * NUM_AUTONS;
		}

		// display auton name
		displayLCDCenteredString(0, autonNames[abs(selectedAuton)]);

		// display auton side
		if (sgn(selectedAuton) == 1) {
			displayLCDCenteredString(1, "RIGHT");
		} else if (sgn(selectedAuton) == -1) {
			displayLCDCenteredString(1, "LEFT");
		} else {
			displayLCDCenteredString(1, "N/A");
		}
	}
}

void pre_auton() {
	startTask(selector);
	calibrate();
	bStopTasksBetweenModes = true;
	bLCDBacklight = true;
}

task autonomous() {
	selectedAuton = 3;
	if (selectedAuton == 0) {
		// deploy
		moveTopLift(127);
		wait1Msec(1200);
		moveTopLift(0);
	} else if (selectedAuton == 1) {
		stationaryGoal(sgn(selectedAuton));
	} else if (selectedAuton == 2) {
		mogo24(sgn(selectedAuton));
	} else if (selectedAuton == 3) {
		displayLCDCenteredString(0, "PSKILLS");
		pskills(sgn(selectedAuton));
	} else if (selectedAuton == 4){
		mogo22(sgn(selectedAuton));
	}
}

// drive code
int leftPower;
int rightPower;
task driveControl() {
	while (true) {
		// dead zone
		leftPower = (abs(vexRT[Ch3] + vexRT[Ch1]) > 20) ? vexRT[Ch3] + vexRT[Ch1] : 0;
		rightPower = (abs(vexRT[Ch3] - vexRT[Ch1]) > 20) ? vexRT[Ch3] - vexRT[Ch1] : 0;

		// apply power
		moveDrive(leftPower, rightPower);
		wait1Msec(20);
	}
}

task autostackControl() {
	while (true) {
		if (vexRT[Btn8L] || vexRT[Btn8LXmtr2])
			abortAutostack();

		if (vexRT[Btn8RXmtr2]) {
			startTask(matchReset);
			waitUntil(SensorValue[MainLiftPot] < 1500);
			abortAutostack();
		}

		wait1Msec(20);
	}
}

int conesOnMogo = 0;

task usercontrol() {
	startTask(selector);
	// initialize drive code for drive
	startTask(driveControl);

	// initialize autostack stopping code
	startTask(autostackControl);

	int clawStall = -15;
	while (true) {
		// LCD code
		//displayLCDNumber(0, 8, conesOnMogo);

		// main lift code
		if (vexRT[Btn7U]) {
			stopTask(mainLiftPI);
			moveMainLift(127);
		} else if (vexRT[Btn7D]) {
			stopTask(mainLiftPI);
			moveMainLift(-127);
		} else {
			int mainLiftPower = (abs(vexRT[Ch3Xmtr2]) > 10) ? vexRT[Ch3Xmtr2] : 0;
			if (mainLiftPower != 0)
				stopTask(mainLiftPI);
			moveMainLift(mainLiftPower);
		}

		// top lift code
		if (vexRT[Btn8U]) {
			stopTask(topLiftPI);
			moveTopLift(127);
			} else if (vexRT[Btn8D]) {
			stopTask(topLiftPI);
			moveTopLift(-127);
			} else {
			int topLiftPower = (abs(vexRT[Ch2Xmtr2]) > 10) ? vexRT[Ch2Xmtr2] : 0;
			if (topLiftPower != 0) {
				stopTask(topLiftPI);
			}
			moveTopLift(topLiftPower);
		}

		// mogo intake code
		if ((vexRT[Btn5U] || vexRT[Btn7UXmtr2]) && SensorValue[MogoPot] < 2690) {
				moveMogoIntake(127); // withdraw mogo intake
			} else if ((vexRT[Btn5D] || vexRT[Btn7DXmtr2]) && SensorValue[MogoPot] > 750) {
				moveMogoIntake(-127); // extend mogo intake
			} else {
				moveMogoIntake(0);
			}


		// cone intake (claw) code
		if (vexRT[Btn6U] && vexRT[Btn6D]) {
			moveConeIntake(15); // stall torque
			} else if (vexRT[Btn6U] || vexRT[Btn6UXmtr2]) {
			moveConeIntake(70); // close cone intake
			clawStall = 10;
			} else if (vexRT[Btn6D] || vexRT[Btn6DXmtr2]) {
			moveConeIntake(-70); // open cone intake
			clawStall = -15;
			} else {
			moveConeIntake(clawStall); // stall cone intake in the right direction
		}

		// autostack
		if (vexRT[Btn8R] || vexRT[Btn8R]) {
			autostack(conesOnMogo, FIELD);
			conesOnMogo++;
		}

		// counter control
		if ((vexRT[Btn7L] || vexRT[Btn7LXmtr2]) && conesOnMogo > 0) {
			waitUntil(!vexRT[Btn7L] || vexRT[Btn7LXmtr2]);
			conesOnMogo--;
		} else if (vexRT[Btn7R] || vexRT[Btn7RXmtr2]) {
			waitUntil(!(vexRT[Btn7R] || vexRT[Btn7RXmtr2]));
			conesOnMogo++;
		}

		/*
		PARTNER STICK EXTRAS
		*/

		if (vexRT[Btn8UXmtr2]) {
			autostack(conesOnMogo, MATCH);
			conesOnMogo++;
		}

		if (vexRT[Btn8DXmtr2]) {
			conesOnMogo = 0;
		}

		if (vexRT[Btn8LXmtr2]) {
			abortAutostack();
		}

		wait1Msec(20);
	}
}
