#pragma config(Sensor, in1,    MainLiftPot,    sensorPotentiometer)
#pragma config(Sensor, in2,    MogoPot,        sensorPotentiometer)
#pragma config(Sensor, in3,    TopLiftPot,     sensorPotentiometer)
#pragma config(Sensor, in5,    Gyro,           sensorGyro)
#pragma config(Sensor, in6,    ConePot,        sensorPotentiometer)
#pragma config(Sensor, dgtl1,  LEncoder,       sensorQuadEncoder)
#pragma config(Sensor, dgtl3,  REncoder,       sensorQuadEncoder)
#pragma config(Motor,  port2,           LDrive,        tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port3,           LMainLift,     tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port4,           ConeIntake,    tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port5,           LMogoIntake,   tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port6,           RMogoIntake,   tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port7,           TopLift,       tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port8,           RMainLift,     tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port9,           RDrive,        tmotorVex393_MC29, openLoop, reversed)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#pragma platform(VEX2)

// Select Download method as "competition"
#pragma competitionControl(Competition)

#include "motor.h"
#include "stall.h"
#include "functions.h"
#include "liftFunctions.h"
#include "autostack.h"
#include "autons.h"

#include "Vex_Competition_Includes.c"

void pre_auton() {
	//calibrate();
  bStopTasksBetweenModes = true;
}
/*
2 bands top left (old, low quality bands)
14 bands top right
10 middle right/left
5 back right/left
*/

task autonomous() {
cone();
}

int conesOnMogo = 0;
task usercontrol() {
	bool stallOn;
	bLCDBacklight = true;
	writeDebugStream("test\n");
	startTask(driveTopLift);
	startTask(driveMainLift);

  while (true) {
  	displayLCDNumber(0, 8, conesOnMogo);
  	// drive code
  	moveDrive(vexRT[Ch3] + vexRT[Ch1], vexRT[Ch3] - vexRT[Ch1]);

  	// mogo intake code\

  	if (vexRT[Btn7U]) {
  		moveMogoIntake(-127);
  	} else if (vexRT[Btn7D]) {
  		moveMogoIntake(127);
  	} else {
  		moveMogoIntake(0);
  	}

  	// cone intake (claw) code
  	if (vexRT[Btn6U]) {
  		moveConeIntake(60);
  	} else if (vexRT[Btn6D]) {
  		moveConeIntake(-60);
  	} else if (vexRT[Btn8L]) {
  		startTask(holdTopLift);
  	} else {
  		clawStall(false);
  	}


  	// autostack code
  	if (vexRT[Btn8R]) {

  	} else if (vexRT[Btn7L] && conesOnMogo > 0) {
  		waitUntil(!vexRT[Btn7L]);
  		conesOnMogo--;
  	} else if (vexRT[Btn7R]) {
  		waitUntil(!vexRT[Btn7R]);
  		conesOnMogo++;
  	}

  	wait1Msec(20);
  }
}
